### ISSUE TITLE
1mac-reservation project sms confirmation added 

### ISSUE THREAD

**Issue by dreamer39** [shadimac/django-Workshops-Arabic#3]
https://github.com/dreamer39/reservation-prog2
is this the best way to send you our code in github?i mean through issues?
i have an issue trnsforming my code into the classes in workshop no. 3 because i have lots of raw inputs i guess!!...do u have any suggestions?

**Comment by ghost** [comment]
Hello dear,
No need to send me the code, that was during the 1MAC initiative 😄, for now you can log here an issue you faced during your implementation and I'll try my best to solve it with you.
