### ISSUE TITLE
my code 

### ISSUE THREAD

**Issue by mahmoudaboalnaga** [shadimac/django-Workshops-Arabic#4]
here my github code ,thanks for your support and your help to continue what we begin
https://github.com/mahmoudaboalnaga/website_hotel_system.git

**Comment by ghost** [comment]
Thank you Mahmoud :), Honestly, I'll not be able to review it 😄, but you still can post here any issues that face you so I'll help you to fix 👍

**Comment by mahmoudaboalnaga** [comment]
Great, I will follow your workshops to the end and for any issue will send you
Thanks
