### ISSUE TITLE
angular  do not import data from server

### ISSUE THREAD

**Issue by elmahdiDev** [shadimac/django-Workshops-Arabic#8]
hi i have a problem that the data on the server is not imported to the page and it shows only sheraton and hilton hotels that there were on hotels list but i deleted them and it steel showing up

my github repo : https://github.com/elmahdiDev/elmahdi_Projects/tree/master/Hotel_Project/hotel_system

**Comment by ahmdadl** [comment]
@elmahdiDev  try to clear your browser cache ``` ctrl + shift + R ``` in windows

**Comment by elmahdiDev** [comment]
it workedddddddddddddddd thank you
